### ISSUE TITLE
go.mod 1.17

### ISSUE THREAD

**Issue by olevenets2** [hoehermann/purple-gowhatsapp#126] opened 2022-07-12 08:41 UTC
Hello, I wanted to compile this plugin on my raspberry pi, having installed all the dependencies, I ran into a problem when building:

> Scanning dependencies of target purple-go-whatsapp
> [ 19%] Updating go modules...
> go mod tidy: go.mod file indicates go 1.17, but maximum supported version is 1.15
> gmake[2]: *** [src/go/CMakeFiles/purple-go-whatsapp.dir/build.make:102: ../src/go/go.mod] Ошибка 1
> gmake[2]: *** Удаляется файл «../src/go/go.mod»
> gmake[1]: *** [CMakeFiles/Makefile2:135: src/go/CMakeFiles/purple-go-whatsapp.dir/all] Ошибка 2
> gmake: *** [Makefile:149: all] Ошибка 2

i tried to manually change the go.mod version to 1.15 but that results in further build errors. Is there any way to build this for the latest Debian stable or could you make changes to the source code?

**Comment by hoehermann** [comment] 2022-07-12 14:11
Unfortunately, using an older version of go is not possible. Current versions of WhatsApp (not just this project, but the actual protocol itself) rely on cryptographic functions which are – as far as I know – only available in go 1.17 or later.

However, the go compiler is rather nomadic. I expect go 1.17 to be available on Debian for arm or Raspbian in some way. Maybe you can upgrade?

Duplicate of https://github.com/hoehermann/purple-gowhatsapp/issues/91#issuecomment-928284262, https://github.com/hoehermann/purple-gowhatsapp/issues/88#issuecomment-892168524, and https://github.com/hoehermann/purple-gowhatsapp/issues/90#issuecomment-1014624374.

**Closed as completed by hoehermann** 2022-07-12 14:11 UTC
