### ISSUE TITLE
Pidgin Whatsapp: Erro during Login error decoding login resp

### ISSUE THREAD

**Issue by Capsis** [hoehermann/purple-gowhatsapp#85] opened 2021-06-23 12:02 UTC
Dear community,

Till now I have been using the whatsapp plugin for pidgin and am grateful for it.
To make it even better I am raising three different issues in three tickets.

This is the second issue:
2.error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}
Here I was using the latest build 0.4.1 in Linux Ubuntu 20.04
I have read about the error. Many people say that it the line 
should be replaced with line 

This was discussed in https://github.com/EionRobb/purple-gowhatsapp/issues/4
https://www.gitmemory.com/issue/dimaskiddo/go-whatsapp-rest/6/499252352
session.go file line number 152.
changing {0, 3, 225} to {0,3,3324} did solved it.

However I do not know where to replace and have issue compiling (see ticket three).

Hopefully this is helpful to resolve this issue and we can see updates .so and dlls which fix this issue.

**Comment by hoehermann** [comment] 2021-06-23 22:36
Hi @Capsis 

`cannot unmarshal array into Go value of type map[string]interface {}` can indeed be caused by an old version number. However, this is fixed in https://github.com/Rhymen/go-whatsapp/commit/2b8a3e9. No further changes should be necessary. Binaries built against this version are provided for Ubuntu 20.04 at https://buildbot.hehoe.de/purple-gowhatsapp/builds/?C=M;O=D.

**Comment by Capsis** [comment] 2021-07-18 12:46
Dear Hoehermann,

The current version works without a problem.
Regards and nice weekend.

**Closed** 2021-07-18 12:46 UTC
