### ISSUE TITLE
Permission issues when building with paru on Arch

### ISSUE THREAD

**Issue by samtrek** [hoehermann/purple-gowhatsapp#170] opened 2023-07-10 06:13 UTC
The error thrown is in this form, will like to know what to do going forward, I am on Archlinux  6.1.38-1-lts

CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "FindPurple.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Purple", but
  CMake did not find one.

  Could not find a package configuration file provided by "Purple" with any
  of the following names:

    PurpleConfig.cmake
    purple-config.cmake

  Add the installation prefix of "Purple" to CMAKE_PREFIX_PATH or set
  "Purple_DIR" to a directory containing one of the above files.  If "Purple"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by hoehermann** [comment] 2023-07-10 08:30
I am now using submodules so I can share code across projects more easily. Please execute `git submodule update --init`.

**Comment by samtrek** [comment] 2023-07-10 10:06
Thank you for your feedback, the copy of the plugin I am using is from the AUR (Arch User Repository) seems the maintainer has not been been seeing to the plugin for awhile, I had to do manual installation to update it.

**Comment by hoehermann** [comment] 2023-07-10 14:08
I am the maintainer. Indeed, I did forgot adjust the PKGBUILD yesterday.

**Comment by samtrek** [comment] 2023-07-10 17:07
Oh, then it will be updated when you have the time to spare, thank you for the good work.

**Comment by hoehermann** [comment] 2023-07-10 18:07
Should be working now. Feel free to leave a message if it does. If it does not, please leave a message anyway. ;)

**Comment by samtrek** [comment] 2023-07-10 19:54
Sorry to bother you once again, it can now be installed through the aur, 
however the issues encountered are as follows
1. the plugin keeps indicating new updates after successful update
2.  the plugin cannot be updated without removing the files downloaded through the aur helper in my own case paru, it has been like this since I have started using this plugins other plugins does not require this process.
3. The plugin leaves a trail of errors some of which I have provided below

rm: cannot remove '/home/$USER/.cache/paru/clone/purple-gowhatsapp-git/src/purple-gowhatsapp/build/src/go/go/pkg/mod/google.golang.org/protobuf@v1.30.0/LICENSE': Permission denied
rm: cannot remove '/home/$USER/.cache/paru/clone/purple-gowhatsapp-git/src/purple-gowhatsapp/build/src/go/go/pkg/mod/google.golang.org/protobuf@v1.30.0/regenerate.bash': Permission denied

I can live with these errors, I have been using it like this for a while, but it will be nice if it can be looked into, once again thank you for your efforts.

**Comment by hoehermann** [comment] 2023-07-10 22:42
Thank you for the information. On my test machine it works flawlessly with `makepkg`. I do not know Arch (or paru for that matter) well enough to resolve this quickly. In case an Arch user could look into this, that would be nice.

**Comment by beadon** [comment] 2023-07-11 00:09
This looks like the build issues I was seeing with DEB.  Basically, anything in the golang build and cache directory is read-only.  I don't know why it's like that, but it's like that every time.

it must be a golang setting at build time , maybe in cmake, but almsot certainly inside go.

**Comment by hoehermann** [comment] 2023-07-11 08:39
Indeed, this is inside go and by design, says https://github.com/golang/go/issues/27161#issuecomment-433102849. Allegedly, one shall use `go clean -modcache` for clean-up. I added an appropriate target `clean-modcache` to CMakeLists.txt. However, there is [no support](https://bbs.archlinux.org/viewtopic.php?id=231878) for clean-up procedures in PKGBUILD. Feel free to re-open this issue in case that is changing. Until then, this is a "wontfix". I am not aware of cpack having clean-up procedure.

**Closed as completed** 2023-07-11 19:31 UTC
Labels: wontfix

**Comment by NetworkJack2** [comment] 2023-10-05 21:07
Late to the party, but I maintain the versioned PKGBUILD, the git submodule --init does not work, I am trying to build release versions, not git.

**Comment by hoehermann** [comment] 2023-10-06 20:13
https://aur.archlinux.org/packages/purple-gowhatsapp-git should be identical with https://github.com/hoehermann/purple-gowhatsapp/blob/whatsmeow/PKGBUILD. Both check out the latest tagged version. I do not actually make use of the github releases page. At least not yet. There is some movement happening at #172. :)

From what I see at https://aur.archlinux.org/packages/purple-gowhatsapp, it is downloading the source archive. That will [not support git submodules](https://stackoverflow.com/questions/34510682/is-there-a-way-to-include-submodules-in-github-download). Maybe you can download the file explicitly?

    wget https://raw.githubusercontent.com/hoehermann/purple-cmake-template/master/purple-config.cmake -O submodules/purple-cmake/purple-config.cmake

Since I am using Ubuntu most of the time, I do not know the benefits of having two variants in the AUR. I never understood how the version information in the project, the PKGBULD and SRCINFO interact. Please note: Due to the static nature of go builds, it is necessary to re-build the plug-in to keep up with the WhatsApp version numbers. Users can get away with using old versions for quite some time, but there is [a new one every other week](https://github.com/tulir/whatsmeow/commits/main)! :o

Since you are familiar with AUR, can you tell me how to delete the outdated comments found at https://aur.archlinux.org/packages/purple-gowhatsapp-git?

**Comment by NetworkJack2** [comment] 2023-10-09 23:39
nvm. I just used a static version of purple-config.cmake, that I just downloaded, and bundled with the PKGBUILD instead of linking. I think this is best, as this is a known good version, instead of linking to a dynamic github object. I will test this file every release, and if needed, import a new one.

Static version that compiles today, should compile tommorrow, with known good cmake file.

Disregard.

edit:
benefits of two packages:
One package is -git version. This pulls whatever is latest
two is based on static releases. This is superior for downstream package management. You have known code, stable releases, and ability to reproduce bugs.

I have my own Arch repo, so I make a lot of static release versions. When possible, I use static releases. Better for quality and management reasons.
