### ISSUE TITLE
Conversation scrollback gone after Pidgin restart

### ISSUE THREAD

**Issue by Zorgodon** [hoehermann/purple-gowhatsapp#187] opened 2024-02-13 14:19 UTC
I'm not sure whether this is intended behaviour, but the messages in the conversation window for a given group chat/IM  with a contact disappear if I quit Pidgin after adding my WA account with fetch-history. I have logging enabled, so I can see the conversation in a separate log window, but the main window gets cleared like there was nothing there.

**Comment by hoehermann** [comment] 2024-02-13 15:14
Thank you for the question. I think you may indeed be describing intended behaviour. By default, Pidgin clears the conversation when the window is closed. You can have logged messages displayed with the "History" `gtk-history` plug-in. The plug-in is shipped with Pidgin. Does that help?

**Comment by hoehermann** [comment] 2024-02-29 03:27
Closing due to lack of answer. In case there are follow-up questions, feel free to leave a comment.

**Closed as not planned by hoehermann** 2024-02-29 03:27 UTC
